name: Check audit setting

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, windows-2022, windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run WELA.ps1 audit-settings
        run: |
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        run: |
          ./WELA.ps1 audit-filesize

      - name: Output UsableRules.csv
        run: |
          Get-Content UsableRules.csv

      - name: Output UnUsableRules.csv
        run: |
          Get-Content UnusableRules.csv